### ISSUE TITLE
Will you add support for1.14.4?

### ISSUE THREAD

**Issue by 1shin-7** [bongoStudios/fauth#1]
I have a 1.14.4Survival Server just in need...
Can you add support for it?

**Comment by ImUrX** [comment]
You could compile this version https://github.com/bongoStudios/fauth/tree/0444db0f301d7f619e66820285eaf429a7ccc668 of fauth

**Comment by ImUrX** [comment]
But it wont have the current features of 1.16

**Comment by 1shin-7** [comment]
ok,thanks
